version: '3.4'

services:
  app: 
    image: daviuz/ruby:3.1.3
    user: root
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    working_dir: /app
    env_file: .env
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    shm_size: 1gb
    ports: 
      - "3000:3000"
    tty: true
    stdin_open: true

volumes:
  gem_cache: